# Generated by Django 3.1 on 2020-09-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200903_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='date',
        ),
    ]
